apiVersion: v1
kind: Pod
metadata:
  name: beegfs-meta
  labels:
    name: beegfs-meta
spec:
  containers:
    - image: redcoolbeans/beegfs-metadata
      name: node02
      env:
        - name: METADATA_SERVICE_ID
          value: "2"
      ports:
        - containerPort: 8005
          protocol: TCP
        - containerPort: 8005
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: node02
  name: node02
spec:
  ports:
  - protocol: TCP
    name: node02-tcp
    port: 8005
    targetPort: 8005
  - protocol: UDP
    name: node02-udp
    port: 8005
    targetPort: 8005
  selector:
    name: beegfs-meta
#  externalIPs:
#  - $EXT_IP1