apiVersion: v1
kind: Pod
metadata:
  name: beegfs-mgmtd
  labels:
    name: beegfs-mgmtd
spec:
  containers:
    - image: redcoolbeans/beegfs-management
      name: node01
      ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 8008
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: node01
  name: node01
spec:
  ports:
  - protocol: TCP
    name: node01-tcp
    port: 8008
    targetPort: 8008
  - protocol: UDP
    name: node01-udp
    port: 8008
    targetPort: 8008
  selector:
    name: beegfs-mgmtd
#  externalIPs:
#  - $EXT_IP1